import { swaggerUI } from "@hono/swagger-ui";
import { Hono } from "hono";
import { generateSpecs } from "hono-openapi";
import type { Env } from "../env.js";
import { PREFIX, authenticate, withStores, type ApiEnv } from "./context.js";
import { notFoundHandler, onError } from "./errors.js";
import { rateLimiters } from "./rate-limit.js";
import { SECURITY_SCHEMES } from "./openapi.js";
import { auth } from "./routes/auth.js";
import { insights } from "./routes/insights.js";
import { notifications } from "./routes/notifications.js";
import { projects } from "./routes/projects.js";
import { replication } from "./routes/replication.js";
import { repositories } from "./routes/repositories.js";
import { tokens } from "./routes/tokens.js";
import { users } from "./routes/users.js";

const DESCRIPTION = `
The control plane of a serverless OCI registry.

The registry API itself lives under \`/v2\` and speaks the OCI distribution
specification; everything here is about managing what it serves - projects,
membership, credentials, retention, replication and the audit log.

**Two planes, two kinds of credential.** A machine token is a data-plane
credential: it exists to pull and push within a declared set of scopes, and is
pinned to exactly one project. It cannot reach the control plane at all, so a
narrow token minted by an administrator can never create another administrator.
The dashboard's session cookie and \`Authorization: Basic\` reach both.

**Rate limits.** Every route is metered per source address, and again per
authenticated principal. Requests that may verify a password are metered a third
time, on a stricter allowance of their own. A refusal is a \`429\` with
\`Retry-After\`.
`.trim();

/**
 * The management API.
 *
 * Built once per isolate and keyed on the bindings, because the rate limiters
 * hold Durable Object stubs that must outlive a single request while `env` is
 * only handed to us with one. A Worker isolate sees the same `env` object on
 * every request it serves, so the map has exactly one entry in practice - and if
 * a runtime ever hands us a fresh one, the cost is rebuilding the router.
 */
const apps = new WeakMap<Env, Hono<ApiEnv>>();

export function apiApp(env: Env): Hono<ApiEnv> {
  const existing = apps.get(env);
  if (existing !== undefined) return existing;

  const app = build(env);
  apps.set(env, app);
  return app;
}

function build(env: Env): Hono<ApiEnv> {
  const app = new Hono<ApiEnv>().basePath(PREFIX);
  const limit = rateLimiters(env);

  app.onError(onError);
  app.notFound(notFoundHandler);

  app.use("*", withStores);

  // Before authenticating, not after: checking a password is the most expensive
  // thing this Worker does, and an unbounded caller must never be able to make
  // us do it on repeat.
  app.use("*", limit.address);
  app.use("*", limit.password);
  app.use("*", authenticate);
  app.use("*", limit.principal);

  app.route("/", auth);
  app.route("/", insights);
  app.route("/", users);
  app.route("/", tokens);
  app.route("/", projects);
  app.route("/", notifications);
  app.route("/", replication);
  // Last: its repository parameter spans slashes, so it is the widest pattern
  // the router holds and must not be offered a path another route wanted.
  app.route("/", repositories);

  // Generated by walking the routes, so it is registered after all of them - and
  // generated exactly once. Walking sixty routes and converting every schema to
  // JSON Schema is real work, and this is the one route an anonymous caller can
  // reach without touching the database; recomputing it per request would make
  // the document an amplifier. The routes cannot change within an isolate, so
  // the answer cannot either. The promise is memoised rather than its value, so
  // concurrent first requests share the one walk.
  let document: Promise<Record<string, unknown>> | undefined;

  app.get("/openapi.json", async (c) => {
    document ??= specOf(app).catch((error: unknown) => {
      // A rejected promise must not be the answer forever.
      document = undefined;
      throw error;
    });

    return c.json(await document);
  });

  app.get("/docs", swaggerUI({ url: `${PREFIX}/openapi.json` }));

  return app;
}

async function specOf(app: Hono<ApiEnv>): Promise<Record<string, unknown>> {
  return generateSpecs(app, {
    documentation: {
      info: {
        title: "Registry management API",
        version: "1.0.0",
        description: DESCRIPTION,
        license: { name: "Apache-2.0", url: "https://www.apache.org/licenses/LICENSE-2.0" },
      },
      // No `servers`: every path already carries the `/api/v1` prefix, so a
      // relative document lets Swagger UI drive whichever origin served it.
      components: { securitySchemes: SECURITY_SCHEMES },
    },
    // The document and the page that renders it describe the API; they are not
    // part of it.
    exclude: [`${PREFIX}/openapi.json`, `${PREFIX}/docs`],
  });
}
